### ISSUE TITLE
Themes slowing down rambox

### ISSUE THREAD

**Issue by FlyingPersian** [obvionaoe/dark#5]
Hello,

first of all, thank you for your work! The themes look great. Unfortunately, they also slow down my rambox extremely.. It's not just the apps I'm using (Messenger, Telegram, WhatsApp & Discord), but also the program itself, e.g. when I open a menu or whatever. Everything is slow. Using just one theme was enough. Any idea what I could do to fix this? I'm running rambox 0.7.3 on Ubuntu 18.04.

**Comment by obvionaoe** [comment]
Hi, I'm currently not using Rambox anymore as I've switched to Ferdi. It is normal for the services to be a little slow while loading for the first time as they have to switch all of the css... Is the app slow even after that initial loading process? If it is, I'm not sure what could be causing this :/ I recommend maybe asking about it over on the Rambox repository, as they might know more about it

**Comment by obvionaoe** [comment]
actually I might have a solution, are you perhaps using the WhatsApp theme?
If you are, try updating to the new version I uploaded, as the old version had a very large size background image that might be making Rambox slower... As of the new version I've removed the background image, because in most resolution you won't even see it

**Comment by FlyingPersian** [comment]
Seems as if the Theme isn't working now. I copied it into the settings, reloaded and restarted rambox, but WA isn't changing. The others (Telegram and Messenger) are still in use and work fine, so WA must have been the issue.

**Comment by obvionaoe** [comment]
What do you mean with WhatsApp not changing? Is it not loading the dark theme?

**Comment by FlyingPersian** [comment]
Exactly! The theme is staying default

**Comment by obvionaoe** [comment]
Ok, my bad!\
I've changed the layout of the repo a little bit as I've moved on from Rambox and want to make the themes compatible with both Ferdi/Franz and Rambox!\
\
The issue is Rambox is different from the other two, as it can't inject `CSS` directly and has to inject a `JS` function that injects the `CSS`. To make the repository more straightforward I moved that function from the theme itself to a different standalone file: [rambox/function.js](https://github.com/obvionaoe/dark/blob/master/rambox/function.js)\
\
For convenience I'll paste the function below:

```js
function applycss(css){
  var head = document.getElementsByTagName('head')[0];
  var s = document.createElement('style');
  s.setAttribute('type', 'text/css');
  s.appendChild(document.createTextNode(css));
  head.appendChild(s);
}

applycss(`[paste css here]`);
```

Just paste the `CSS` from [whatsapp/darkmode.css](https://github.com/obvionaoe/dark/blob/master/whatsapp/darkmode.css) where it says `[paste css here]`, DON'T remove the back-ticks!\
And then paste everything into the box on the Rambox service.\
\
Let me know if it works!

**Comment by FlyingPersian** [comment]
Works like a sharm now! Thank you very much for your effort and support!
