### ISSUE TITLE
Letter 'A' near the date in TELEGRAM

### ISSUE THREAD

**Issue by alzedd** [obvionaoe/dark#8]
You can se a big 'A' at the start and at the end of the date box

![immagine](https://user-images.githubusercontent.com/29459468/81405538-2305cc00-9138-11ea-8d57-43561766d962.png)

**Comment by obvionaoe** [comment]
Hi, I'm not able to reproduce this... Could you give me some extra details?

**Comment by alzedd** [comment]
Yes, sorry. I didn't read that you don't support Rambox, that's what I am using right now... 

I just copied and pasted inside the custom code in rambox the js code to put the css in the page ([this](https://gist.github.com/orevial/80aee6032d6ca1faffeaa72d8581f5eb))

**Comment by obvionaoe** [comment]
Let me install Rambox and test this, and I'll get back to you

**Comment by obvionaoe** [comment]
Ok, I found out what the problem is, it's related to Rambox and not the theme!\
I think it's something in the way Rambox injects the CSS, because that "A" comes from a line break character ("\A") and Rambox is leaving out the slash when it injects it.

I'd try asking on their repo! 

PS: If no one answers you over there just replace the "\A" in the darkmode.css with "\\\A", it should solve the problem, but it is only a temporary fix!

**Comment by alzedd** [comment]
hey, thank you @obvionaoe. I'll try to add the double backslash then, no problem. 

Closing since it solved :)
